"""Utility modules for progress tracking and state management."""

from vtsearch.utils.progress import get_progress, get_sort_progress, update_progress, update_sort_progress
from vtsearch.utils.state import (
    add_favorite_detector,
    add_favorite_extractor,
    add_label_to_history,
    bad_votes,
    build_clip_lookup,
    clear_all,
    clear_clips,
    clear_votes,
    clips,
    dataset_creation_info,
    favorite_detectors,
    favorite_extractors,
    get_dataset_creation_info,
    get_favorite_detectors,
    get_favorite_detectors_by_media,
    get_favorite_extractors,
    get_favorite_extractors_by_media,
    get_inclusion,
    good_votes,
    inclusion,
    label_history,
    remove_favorite_detector,
    remove_favorite_extractor,
    rename_favorite_detector,
    rename_favorite_extractor,
    resolve_clip_ids,
    set_dataset_creation_info,
    set_inclusion,
)

__all__ = [
    # Progress
    "update_progress",
    "get_progress",
    "update_sort_progress",
    "get_sort_progress",
    # State
    "clips",
    "good_votes",
    "bad_votes",
    "label_history",
    "inclusion",
    "dataset_creation_info",
    "favorite_detectors",
    "favorite_extractors",
    "clear_votes",
    "clear_clips",
    "clear_all",
    "get_inclusion",
    "set_inclusion",
    "add_label_to_history",
    "set_dataset_creation_info",
    "get_dataset_creation_info",
    "add_favorite_detector",
    "remove_favorite_detector",
    "rename_favorite_detector",
    "get_favorite_detectors",
    "get_favorite_detectors_by_media",
    "add_favorite_extractor",
    "remove_favorite_extractor",
    "rename_favorite_extractor",
    "get_favorite_extractors",
    "get_favorite_extractors_by_media",
    "build_clip_lookup",
    "resolve_clip_ids",
]
